name: paper-summary-tweet-notification

on:
  schedule:
    # UTC 0時 -> 日本時間朝9時
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.0

      - name: Install packages
        run: poetry install --no-dev

      - name: paper-tweet-notification
        run: poetry run python src/main.py
        env:
          SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
